name 'brucem-ezpublish'
version '0.3.0'
source 'git://github.com/brucem/puppet-ezpublish.git'
author 'Bruce Morrison'
license 'Apache 2.0'
summary 'eZ Publish Module'
description 'eZ Publish Module'
project_page 'http://github.com/brucem/puppet-ezpublish'
dependency 'puppetlabs/mysql',  '2.2.x'
dependency 'puppetlabs/apache', '1.0.x'
dependency 'example42/php', '2.0.x'
